name: Pack to NuGet

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: | 
          dotnet pack ./src/Irihi.Avalonia.Shared -o ./nugets
          dotnet pack ./src/Irihi.Avalonia.Shared.Contracts -o ./nugets
    - name: Publish NuGet package
      if: ${{ inputs.Upload_to_NuGet }}
      run: dotnet nuget push "./nugets/*.nupkg" --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Upload a Build Artifact 
      uses: actions/upload-artifact@v7
      with:
        name: nugets
        path: nugets
      if: always()