name: Pack to NuGet

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: | 
          dotnet pack ./src/Irihi.Avalonia.Shared -o ./nugets
          dotnet pack ./src/Irihi.Avalonia.Shared.Contracts -o ./nugets
    - name: Publish NuGet package
      run: dotnet nuget push "./nugets/*.nupkg" --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
