# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pack and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build --no-restore ./src
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src
    - name: Pack
      run: dotnet pack ./src/Irihi.Avalonia.Shared -o ./nugets
    - name: Publish NuGet package
      run: dotnet nuget push "./nugets/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
