name: Release Tag

on:
  workflow_dispatch:
    inputs:
      Upload_to_NuGet:
        description: 'Upload to NuGet'
        default: false
        type: boolean

jobs:
  nuget:
    uses: ./.github/workflows/pack.yml
    with:
      Upload_to_NuGet: ${{ inputs.Upload_to_NuGet }}
    secrets: inherit

  draft-release:
    needs: [ nuget ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          generate_release_notes: true
          draft: true
          files: |
            nugets/*.nupkg
