name: Release Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Restore dependencies
        run: dotnet restore ./src
      - name: Build
        run: dotnet build --no-restore ./src
      - name: Test
        run: dotnet test --no-build --verbosity normal ./src
      - name: Pack
        run: |
          dotnet pack ./src/Irihi.Avalonia.Shared -o ./nugets
          dotnet pack ./src/Irihi.Avalonia.Shared.Contracts -o ./nugets
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          generate_release_notes: true
          draft: true
          files: |
            *.nupkg
